#pragma once

#include "Fraction.h"

class Justize
{
public:
	enum JUSTIZE_PARTS { WAPON, DRUG, INFORMATION, TEKK, TRAVELLER, PSIONIK, END};
	enum REAKTION {NOT, CONTROL, INSPECTION, FIGHT};
	enum CONFLIKT_TYPE {FIRST_CONTACT, DAYLY_VISIT, CREEPY_PERSON, BAR_FIGHT, GUN_FIER, RAID, HAVY_GUN_FIGHT, SLAYING};
	enum JUDGEMENT{NOTHING, MONEY_1x1, MONEY_2x5, MONEY_2x10, PRISION_MONTH, PRISION_YEAR, PRISION_YEARx2, PRISION_FOREVER, DEATH};
	enum ACT {FIGHT, DESTROY, WRING_ID, DETAH, SLAYING};
	Justize(uint8_t mainFractionType);
	REAKTION conflikt(CONFLIKT_TYPE cT);
	JUDGEMENT judge(ACT act);
	JUDGEMENT judgeSmuggle(uint8_t lvlGood);
private:
	uint8_t justizeLvl[END - 1];
};